apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ulykz9oos-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ulykz9oos-python 
  name: ulykz9oos-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ulykz9oos-python 
